# Generated by Django 4.2.7 on 2023-11-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GameSettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesettings",
            name="faction",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="gamesettings",
            name="gameMode",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="gamesettings",
            name="passHomeScreen",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
