# Generated by Django 4.2.7 on 2023-11-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GameSettings", "0002_alter_gamesettings_faction_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="GameSettings", new_name="GameSetting",),
    ]
