# Generated by Django 4.2.7 on 2023-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GameSettings", "0003_rename_gamesettings_gamesetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winner", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
