# Generated by Django 4.2.7 on 2023-11-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GameSettings", "0004_winner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="winner", old_name="winner", new_name="sideWinner",
        ),
    ]
