# Generated by Django 4.2.7 on 2023-11-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributesOf", models.CharField(default="", max_length=50)),
                ("armor", models.FloatField()),
                ("power", models.FloatField()),
                ("stamina", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Mob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("raid", models.CharField(max_length=8)),
                ("level", models.CharField(max_length=15)),
                (
                    "attributes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Mob.attributes"
                    ),
                ),
            ],
        ),
    ]
