# Generated by Django 4.2.7 on 2023-11-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Mob", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Attributes", new_name="Attribute",),
    ]
