# Generated by Django 4.2.7 on 2023-12-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Skill", "0001_initial"),
        ("Mob", "0002_rename_attributes_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="mob",
            name="skill",
            field=models.ManyToManyField(to="Skill.skill"),
        ),
    ]
