# Generated by Django 5.0.1 on 2024-01-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
