# Generated by Django 4.2.7 on 2023-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="durationEffect",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
