# Generated by Django 5.0.1 on 2024-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0002_skill_durationeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
