# Generated by Django 4.2.7 on 2023-11-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PvESetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raid", models.IntegerField(blank=True, default=0)),
                ("easyMob", models.CharField(blank=True, max_length=55)),
                ("mediumMob", models.CharField(blank=True, max_length=55)),
                ("hardMob", models.CharField(blank=True, max_length=55)),
                ("bossMob", models.CharField(blank=True, max_length=55)),
            ],
        ),
    ]
