# Generated by Django 4.2.7 on 2023-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="characterSelect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tank", models.CharField(blank=True, max_length=50)),
                ("melee", models.CharField(blank=True, max_length=50)),
                ("ranged", models.CharField(blank=True, max_length=50)),
                ("heal", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
