# Generated by Django 4.2.7 on 2023-11-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Character", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributes",
            name="attributesOf",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="path",
            name="pathOf",
            field=models.CharField(default="", max_length=50),
        ),
    ]
