# Generated by Django 4.2.7 on 2023-11-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Character", "0002_attributes_attributesof_path_pathof"),
    ]

    operations = [
        migrations.RemoveField(model_name="character", name="path",),
        migrations.DeleteModel(name="Path",),
    ]
