# Generated by Django 5.0.1 on 2024-01-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0008_character_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.CharField(blank=True, default='', max_length=550),
        ),
    ]
