# Generated by Django 5.0.1 on 2024-01-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageManager', '0001_initial'),
        ('WebsiteContent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePagePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('subtitle', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ImageManager.uploadedimage')),
            ],
        ),
        migrations.DeleteModel(
            name='homePageCard',
        ),
    ]
