# Generated by Django 5.0.1 on 2024-01-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteContent', '0002_homepagepanel_delete_homepagecard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homePagePanel',
        ),
    ]
