# Generated by Django 5.0.1 on 2024-01-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageManager', '0001_initial'),
        ('WebsiteContent', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepanel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageManager.uploadedimage'),
        ),
    ]
