# Generated by Django 5.0.1 on 2024-01-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteContent', '0005_alter_homepagepanel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagepanel',
            old_name='image',
            new_name='imageManager',
        ),
    ]
