# Generated by Django 5.0.1 on 2024-01-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteContent', '0006_rename_image_homepagepanel_imagemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepanel',
            name='link',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
