# Generated by Django 5.0.1 on 2024-01-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageManager', '0001_initial'),
        ('WebsiteContent', '0007_homepagepanel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=55)),
                ('link', models.CharField(max_length=55)),
                ('style', models.CharField(max_length=55)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageManager.uploadedimage')),
            ],
        ),
    ]
