# Generated by Django 5.0.1 on 2024-01-26 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageManager', '0001_initial'),
        ('WebsiteContent', '0009_button_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('subtitle', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('page', models.CharField(blank=True, max_length=55, null=True)),
                ('style', models.CharField(blank=True, max_length=55, null=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageManager.uploadedimage')),
                ('buttons', models.ManyToManyField(to='WebsiteContent.button')),
                ('imageContent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImageUploaded2ContentImage', to='ImageManager.uploadedimage')),
            ],
        ),
    ]
