# Generated by Django 5.0.1 on 2024-01-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageManager', '0001_initial'),
        ('WebsiteContent', '0010_headerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('subtitle', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=155, null=True)),
                ('page', models.CharField(blank=True, max_length=55, null=True)),
                ('style', models.CharField(blank=True, max_length=55, null=True)),
                ('BackgroundSectionPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageManager.uploadedimage')),
                ('ImageSectionPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImageUploaded2ImageSectionPage', to='ImageManager.uploadedimage')),
            ],
        ),
    ]
