# Generated by Django 5.0.1 on 2024-01-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteContent', '0011_sectionpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionPage',
        ),
    ]
