# Generated by Django 5.0.1 on 2024-01-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageManager', '0001_initial'),
        ('WebsiteContent', '0013_sectionpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionPage',
            new_name='SectionPagePanel',
        ),
    ]
