# Generated by Django 5.0.1 on 2024-01-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteContent', '0015_alter_sectionpagepanel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerpage',
            name='buttons',
            field=models.ManyToManyField(blank=True, to='WebsiteContent.button'),
        ),
    ]
