# Generated by Django 5.0.1 on 2024-01-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteContent', '0018_alter_sectionpagepanel_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionpagepanel',
            name='imageSectionPage',
        ),
    ]
