# Generated by Django 5.0.1 on 2024-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteContent', '0019_remove_sectionpagepanel_imagesectionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpagepanel',
            name='sectionID',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
