# Generated by Django 4.2.7 on 2023-11-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Character", "0007_rename_attributes_attribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currentArmor", models.FloatField(blank=True, default=0)),
                ("currentPower", models.FloatField(blank=True, default=0)),
                ("currentStamina", models.FloatField(blank=True, default=0)),
                (
                    "characterCard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Character.character",
                    ),
                ),
            ],
        ),
    ]
