# Generated by Django 4.2.7 on 2023-12-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Mob", "0002_rename_attributes_attribute"),
        ("Character", "0007_rename_attributes_attribute"),
        ("Cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="mobCard",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="Mob.mob"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="characterCard",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Character.character",
            ),
        ),
    ]
