# Generated by Django 4.2.7 on 2023-12-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cards", "0004_skillofcard_effecton"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillofcard",
            name="remainingEffect",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
